name: CI/CD Demo

on:
  push:
    branches:
      - main

jobs:
  html-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print message
        run: echo "CI/CD ажиллаж байна"

      - name: Force error
        run: exit 1

      - name: Success message
        run: echo "Success"