name: CI/CD Demo

on:
  push:
    branches:
      - main

jobs:
  demo-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show repository files
        run: ls

      - name: Print branch name
        run: echo "Current branch is main"

      - name: Print CI message
        run: echo "CI/CD pipeline ажиллаж байна"

      - name: Final success message
        run: echo "Workflow completed successfully"